### ISSUE TITLE
Anomaly support?

### ISSUE THREAD

**Issue by Wasmachineman-NL** [Thom-Rum/Call-Of-Chernobyl-Relay-Chat#5]
Since Anomaly is based on Last Day which itself is basically based on CoC, could a Anomaly port be possible for this mod?

**Comment by Thom-Rum** [comment]
Hey man
There's a separate mod which supports Anomaly only:
https://github.com/itsAnchorpoint/Chernobyl-Relay-Chat-Rebirth
